import Head from "next/head";
import Navbar from "../components/Navbar";
import Homepage from "../components/Homepage";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>John Asare| Frontend Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <Navbar />
          <Homepage />
        </section>
        <About />
        <Skills />
        <Projects />
      </main>
    </div>
  );
}
